DROP TABLE IF EXISTS seen;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS workplaces;
DROP TYPE IF EXISTS post_type;
DROP TYPE IF EXISTS user_type;
DROP TYPE IF EXISTS wp_type;