CREATE TYPE wp_type AS ENUM('project', 'team', 'company', 'orginization');
CREATE TYPE user_type AS ENUM('creator', 'user', 'pending');
CREATE TYPE post_type AS ENUM('idea', 'posts');

CREATE TABLE workplaces (
    wp_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wp_name TEXT NOT NULL,
    wp_code TEXT NOT NULL,
    type wp_type
);

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    wp_id INTEGER REFERENCES workplaces(wp_id) ON DELETE CASCADE NOT NULL,
    wp_name TEXT NOT NULL,
    type user_type NOT NULL,
    nickname TEXT,
    img TEXT
);

CREATE TABLE posts (
    post_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    priority INTEGER NOT NULL,
    user_img TEXT NOT NULL,
    type post_type NOT NULL,
    wp_id INTEGER REFERENCES workplaces(wp_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE seen (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    post_id INTEGER REFERENCES posts(post_id) ON DELETE CASCADE NOT NULL
);